"""
backend/app/services/llm.py
----------------------------
High-reliability Google Gemini LLM service for IP-SAKTI Sahayak.
Integrates Key Pool rotation, retry backoff with tenacity, prompt builder,
and non-blocking execution via asyncio.to_thread.
"""

from __future__ import annotations

import asyncio
import logging
from typing import AsyncIterator, Iterator, Optional

from google import genai
from google.genai import types as genai_types
from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_exponential

from app.core.config import settings
from app.services.key_manager import key_manager
from app.services.prompt_builder import prompt_builder

log = logging.getLogger("app.services.llm")


def _get_client_and_key() -> tuple[genai.Client, str]:
    """Retrieves an active client configured with a rotated key."""
    active_key = key_manager.get_active_key()
    client = genai.Client(api_key=active_key)
    return client, active_key


@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=1, max=6),
    reraise=True,
)
def generate_grounded_answer(
    question: str,
    context: str,
    jurisdiction: str = "India",
    language: str = "EN",
    answer_mode: str = "standard",
    user_context: Optional[dict] = None,
    product_context: Optional[dict] = None,
    user_intent: Optional[str] = None,
    requested_information: Optional[Union[list[str], str]] = None,
) -> str:
    """
    Synchronous call to Google Gemini with automatic key rotation and retry logic.
    """
    client, active_key = _get_client_and_key()
    user_prompt = prompt_builder.build_user_prompt(
        question=question,
        context=context,
        jurisdiction=jurisdiction,
        language=language,
        answer_mode=answer_mode,
        user_context=user_context,
        product_context=product_context,
        user_intent=user_intent,
        requested_information=requested_information,
    )

    try:
        response = client.models.generate_content(
            model=settings.PRIMARY_MODEL,
            contents=user_prompt,
            config=genai_types.GenerateContentConfig(
                system_instruction=prompt_builder.SYSTEM_PROMPT,
                temperature=0.2,  # Low temperature for factual precision
                top_p=0.9,
                max_output_tokens=3500,
            ),
        )
        return response.text or "No response generated by model."

    except Exception as e:
        err_msg = str(e).lower()
        if "429" in err_msg or "resource_exhausted" in err_msg or "quota" in err_msg:
            log.warning("Rate limit hit on key ...%s. Rotating key and retrying...", active_key[-6:])
            key_manager.mark_rate_limited(active_key)
        log.error("Gemini generation error: %s", e)
        raise


async def async_generate_grounded_answer(
    question: str,
    context: str,
    jurisdiction: str = "India",
    language: str = "EN",
    answer_mode: str = "standard",
    user_context: Optional[dict] = None,
    product_context: Optional[dict] = None,
    user_intent: Optional[str] = None,
    requested_information: Optional[Union[list[str], str]] = None,
) -> str:
    """
    Asynchronous non-blocking wrapper running Gemini generation in worker thread.
    """
    return await asyncio.to_thread(
        generate_grounded_answer,
        question=question,
        context=context,
        jurisdiction=jurisdiction,
        language=language,
        answer_mode=answer_mode,
        user_context=user_context,
        product_context=product_context,
        user_intent=user_intent,
        requested_information=requested_information,
    )


def stream_grounded_answer(
    question: str,
    context: str,
    jurisdiction: str = "India",
    language: str = "EN",
    answer_mode: str = "standard",
    user_context: Optional[dict] = None,
    product_context: Optional[dict] = None,
    user_intent: Optional[str] = None,
    requested_information: Optional[Union[list[str], str]] = None,
) -> Iterator[str]:
    """
    Streams response tokens from Google Gemini.
    """
    client, active_key = _get_client_and_key()
    user_prompt = prompt_builder.build_user_prompt(
        question=question,
        context=context,
        jurisdiction=jurisdiction,
        language=language,
        answer_mode=answer_mode,
        user_context=user_context,
        product_context=product_context,
        user_intent=user_intent,
        requested_information=requested_information,
    )

    try:
        response_stream = client.models.generate_content_stream(
            model=settings.PRIMARY_MODEL,
            contents=user_prompt,
            config=genai_types.GenerateContentConfig(
                system_instruction=prompt_builder.SYSTEM_PROMPT,
                temperature=0.2,
                top_p=0.9,
                max_output_tokens=3500,
            ),
        )
        for chunk in response_stream:
            if chunk.text:
                yield chunk.text
    except Exception as e:
        log.error("Gemini streaming error: %s", e)
        yield f"\n[Generation error: {e}]"
