"""
backend/app/services/llm_service.py
------------------------------------
Grounded LangChain Gemini LLM Service for IP-SAKTI Sahayak.
Uses ChatGoogleGenerativeAI with dynamic output token limits,
GeminiKeyPool rotation, and non-blocking async execution.
"""

from __future__ import annotations

import asyncio
import logging
from typing import Optional

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_google_genai import ChatGoogleGenerativeAI

from app.core.config import settings
from app.core.gemini_pool import (
    ResourceExhaustedError,
    gemini_key_pool,
    execute_with_retry_and_fallback,
)

log = logging.getLogger("app.services.llm_service")

# ---------------------------------------------------------------------------
# System Prompt (exact specification from Prompt 20)
# ---------------------------------------------------------------------------
_SYSTEM_PROMPT = (
    "You are IP-SAKTI Sahayak, an authoritative legal guide for Ayurvedic Intellectual Property.\n"
    "You MUST answer the user's question using ONLY the retrieved source passages provided below.\n"
    "- If the retrieved context contains the answer, explain it simply and mention the exact legal acts/schedules.\n"
    "- If context is missing or insufficient, state clearly: 'I cannot find an authoritative source "
    "in our legal registers to safely answer this.'\n"
    "- Never invent statutory sections or rules. Keep tone calm, objective, and professional."
)

# Token limits per answer mode
_TOKEN_LIMITS = {
    "brief": 400,
    "standard": 800,
    "detailed": 1400,
}


def _build_llm_call(
    query: str,
    context_str: str,
    answer_mode: str = "standard",
    jurisdiction: str = "India",
    api_key: str = "",
) -> str:
    """
    Synchronous LLM call using LangChain ChatGoogleGenerativeAI.
    Intended to be executed via asyncio.to_thread or execute_with_retry_and_fallback.
    """
    max_tokens = _TOKEN_LIMITS.get(answer_mode.lower(), 800)

    llm = ChatGoogleGenerativeAI(
        model=settings.PRIMARY_MODEL,
        google_api_key=api_key,
        temperature=0.2,
        top_p=0.9,
        max_output_tokens=max_tokens,
    )

    jur_norm = (jurisdiction or "India").strip().lower()
    selected_jurisdiction = (
        "both" if jur_norm == "both"
        else "international" if "international" in jur_norm
        else "india"
    )
    jurisdiction_instruction = (
        f"selected_jurisdiction: {selected_jurisdiction}\n"
        "You are answering a jurisdiction-aware question. Ground every material claim in the "
        "retrieved sources relevant to the selected jurisdiction. Do not generalize rules from one "
        "jurisdiction to another. If the retrieved evidence is insufficient, explicitly state that the "
        "available sources do not support a reliable answer. For every factual or legal claim, provide "
        "an inline citation to the supporting source. When the selected jurisdiction is 'both', separate "
        "India-specific and international conclusions clearly and explain any conflict or difference "
        "between them.\n"
    )

    messages = [
        SystemMessage(content=_SYSTEM_PROMPT),
        HumanMessage(
            content=(
                f"{jurisdiction_instruction}\n"
                f"--- RETRIEVED LEGAL CONTEXT ---\n"
                f"{context_str if context_str.strip() else '[No relevant statutory passages retrieved]'}\n"
                f"--- END CONTEXT ---\n\n"
                f"USER QUESTION:\n{query}\n\n"
                f"Answer mode: {answer_mode.upper()}. "
                f"Provide your citation-grounded statutory answer:"
            )
        ),
    ]

    try:
        response = llm.invoke(messages)
        content = response.content
        # Gemini 3.x may return content as list[dict] with text blocks
        # instead of a plain string. Normalize to str.
        if isinstance(content, list):
            content = "".join(
                block.get("text", "") if isinstance(block, dict) else str(block)
                for block in content
            )
        return content or "No response generated by model."
    except Exception as e:
        err_msg = str(e).lower()
        if "429" in err_msg or "resource_exhausted" in err_msg or "quota" in err_msg:
            gemini_key_pool.mark_key_failed(api_key, status_code=429)
        elif "500" in err_msg or "503" in err_msg:
            gemini_key_pool.mark_key_failed(api_key, status_code=500)
        raise


async def generate_grounded_answer(
    query: str,
    context_str: str,
    answer_mode: str = "standard",
    jurisdiction: str = "India",
) -> str:
    """
    Generates a grounded legal answer using Google Gemini via LangChain
    with automatic key rotation and retry on transient errors.

    Parameters
    ----------
    query : str
        The user's legal question (PII-scrubbed).
    context_str : str
        Formatted context string from retrieved and compressed passages.
    answer_mode : str
        Output depth: "brief" (400 tokens), "standard" (800), "detailed" (1400).

    Returns
    -------
    str
        Generated answer text from Gemini.
    """
    try:
        answer = await execute_with_retry_and_fallback(
            _build_llm_call,
            query=query,
            context_str=context_str,
            answer_mode=answer_mode,
            jurisdiction=jurisdiction,
        )
        return answer

    except ResourceExhaustedError:
        log.error("All Gemini API keys exhausted after retries.")
        return (
            "All API keys are currently rate-limited. Please try again in a few minutes. "
            "If this persists, contact your system administrator."
        )
    except Exception as e:
        log.error("LLM generation failed: %s", e, exc_info=True)
        return (
            "An error occurred while connecting to the statutory reasoning engine. "
            "Please verify that your Gemini API key is valid and try again."
        )
