"""
backend/app/services/llm_service.py
------------------------------------
Grounded LangChain Gemini LLM Service for IP-SAKTI Sahayak.
Uses ChatGoogleGenerativeAI with dynamic output token limits,
GeminiKeyPool rotation, and non-blocking async execution.
"""

from __future__ import annotations

import asyncio
import logging
from typing import Optional

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_google_genai import ChatGoogleGenerativeAI

from app.core.config import settings
from app.core.gemini_pool import (
    ResourceExhaustedError,
    gemini_key_pool,
    execute_with_retry_and_fallback,
)

from app.services.prompt_builder import prompt_builder

log = logging.getLogger("app.services.llm_service")

# Token limits per answer mode (expanded for comprehensive multi-section legal analysis)
_TOKEN_LIMITS = {
    "brief": 800,
    "standard": 2048,
    "detailed": 3500,
}


def _build_llm_call(
    query: str,
    context_str: str,
    answer_mode: str = "standard",
    jurisdiction: str = "India",
    language: str = "EN",
    user_context: Optional[dict] = None,
    product_context: Optional[dict] = None,
    user_intent: Optional[str] = None,
    requested_information: Optional[Union[list[str], str]] = None,
    api_key: str = "",
) -> str:
    """
    Synchronous LLM call using LangChain ChatGoogleGenerativeAI.
    Intended to be executed via asyncio.to_thread or execute_with_retry_and_fallback.
    """
    max_tokens = _TOKEN_LIMITS.get(answer_mode.lower(), 2048)

    llm = ChatGoogleGenerativeAI(
        model=settings.PRIMARY_MODEL,
        google_api_key=api_key,
        temperature=0.2,
        top_p=0.9,
        max_output_tokens=max_tokens,
    )

    user_prompt = prompt_builder.build_user_prompt(
        question=query,
        context=context_str,
        jurisdiction=jurisdiction,
        language=language,
        answer_mode=answer_mode,
        user_context=user_context,
        product_context=product_context,
        user_intent=user_intent,
        requested_information=requested_information,
    )

    messages = [
        SystemMessage(content=prompt_builder.SYSTEM_PROMPT),
        HumanMessage(content=user_prompt),
    ]

    try:
        response = llm.invoke(messages)
        content = response.content
        # Gemini 3.x may return content as list[dict] with text blocks
        # instead of a plain string. Normalize to str.
        if isinstance(content, list):
            content = "".join(
                block.get("text", "") if isinstance(block, dict) else str(block)
                for block in content
            )
        return content or "No response generated by model."
    except Exception as e:
        err_msg = str(e).lower()
        if "429" in err_msg or "resource_exhausted" in err_msg or "quota" in err_msg:
            gemini_key_pool.mark_key_failed(api_key, status_code=429)
        elif "500" in err_msg or "503" in err_msg:
            gemini_key_pool.mark_key_failed(api_key, status_code=500)
        raise


async def generate_grounded_answer(
    query: str,
    context_str: str,
    answer_mode: str = "standard",
    jurisdiction: str = "India",
    language: str = "EN",
    user_context: Optional[dict] = None,
    product_context: Optional[dict] = None,
    user_intent: Optional[str] = None,
    requested_information: Optional[Union[list[str], str]] = None,
) -> str:
    """
    Generates a grounded legal answer using Google Gemini via LangChain
    with automatic key rotation, master prompt architecture, and retry on transient errors.

    Parameters
    ----------
    query : str
        The user's legal question (PII-scrubbed).
    context_str : str
        Formatted context string from retrieved and compressed passages with SOURCE_IDs.
    answer_mode : str
        Output depth: "brief" (800 tokens), "standard" (2048), "detailed" (3500).
    jurisdiction : str
        Active jurisdiction ("India", "International", or "Both").
    language : str
        Response language code ("EN", "HI", etc.).

    Returns
    -------
    str
        Generated answer text from Gemini.
    """
    try:
        answer = await execute_with_retry_and_fallback(
            _build_llm_call,
            query=query,
            context_str=context_str,
            answer_mode=answer_mode,
            jurisdiction=jurisdiction,
            language=language,
            user_context=user_context,
            product_context=product_context,
            user_intent=user_intent,
            requested_information=requested_information,
        )
        return answer

    except ResourceExhaustedError:
        log.error("All Gemini API keys exhausted after retries.")
        return (
            "All API keys are currently rate-limited. Please try again in a few minutes. "
            "If this persists, contact your system administrator."
        )
    except Exception as e:
        log.error("LLM generation failed: %s", e, exc_info=True)
        return (
            "An error occurred while connecting to the statutory reasoning engine. "
            "Please verify that your Gemini API key is valid and try again."
        )
