#!/usr/bin/env python3
"""
build-source-catalog.py
Rebuilds manifests/source-catalog.yaml and manifests/current-versions.yaml from source.yaml files.
"""

import os
import sys
import yaml
from pathlib import Path

def main():
    root_dir = Path(__file__).resolve().parent.parent
    sources_dir = root_dir / "sources"
    manifests_dir = root_dir / "manifests"
    manifests_dir.mkdir(exist_ok=True)

    catalog_entries = []
    current_versions = {}

    for pkg_dir in sources_dir.glob("**/*"):
        source_yaml = pkg_dir / "source.yaml"
        current_yaml = pkg_dir / "current.yaml"
        if source_yaml.is_file():
            with open(source_yaml, "r", encoding="utf-8") as f:
                s_data = yaml.safe_load(f) or {}
            c_data = {}
            if current_yaml.is_file():
                with open(current_yaml, "r", encoding="utf-8") as f:
                    c_data = yaml.safe_load(f) or {}

            source_id = s_data.get("source_id")
            current_v = c_data.get("current_version", "unknown")
            rel_path = pkg_dir.relative_to(root_dir).as_posix()

            catalog_entries.append({
                "source_id": source_id,
                "title": s_data.get("title"),
                "short_title": s_data.get("short_title", ""),
                "jurisdiction": s_data.get("jurisdiction"),
                "source_type": s_data.get("source_type"),
                "issuing_authority": s_data.get("issuing_authority"),
                "current_version": current_v,
                "package_path": rel_path,
                "verification_status": s_data.get("verification_status", "pending-review")
            })

            current_versions[source_id] = {
                "current_version": current_v,
                "source_type": s_data.get("source_type"),
                "jurisdiction": s_data.get("jurisdiction"),
                "relative_path": f"{rel_path}/versions/{current_v}"
            }

    catalog_entries.sort(key=lambda x: (x.get("jurisdiction") or "", x.get("source_type") or "", x.get("source_id") or ""))

    # Write source-catalog.yaml
    cat_path = manifests_dir / "source-catalog.yaml"
    with open(cat_path, "w", encoding="utf-8") as f:
        f.write("# Master Source Catalog for IP-SAKTI Sahayak Knowledge Base\n# Auto-generated by build-source-catalog.py\n\n")
        yaml.dump({
            "catalog_version": "1.0.0",
            "last_updated": "2026-09-14",
            "total_sources": len(catalog_entries),
            "sources": catalog_entries
        }, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    # Write current-versions.yaml
    cur_path = manifests_dir / "current-versions.yaml"
    with open(cur_path, "w", encoding="utf-8") as f:
        f.write("# Current Active Version Manifest\n# Auto-generated by build-source-catalog.py\n\n")
        yaml.dump({
            "manifest_version": "1.0.0",
            "last_updated": "2026-09-14",
            "sources": current_versions
        }, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    print(f"[OK] Rebuilt catalog with {len(catalog_entries)} sources.")

if __name__ == "__main__":
    main()
